openapi: 3.0.0
info:
  title: Labguru Antibodies Comments API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Comments
paths:
  /api/v1/comments:
    post:
      summary: Creates a comment
      tags:
      - Comments
      parameters: []
      responses:
        '201':
          description: comment created
        '422':
          description: invalid request - Name can't be blank
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createComment'
        required: true
    get:
      summary: List all comments in your account
      tags:
      - Comments
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: the default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: ' show summarized data information - true/false'
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
  /api/v1/comments/{id}:
    get:
      summary: Get comment by id
      tags:
      - Comments
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: comment id
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: comment not found
components:
  schemas:
    createComment:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          required:
          - comment
          - commentable_id
          - commentable_type
          properties:
            comment:
              type: string
              description: The text content of the comment
            commentable_id:
              type: integer
              description: The id of the item to which the comment is being added
            commentable_type:
              type: string
              description: Specifies the class name of the item to which the comment is attached, such as Biocollections::Plasmid
