openapi: 3.0.0
info:
  title: Labguru Antibodies Companies API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Companies
paths:
  /api/v1/companies:
    post:
      summary: Add a company
      tags:
      - Companies
      parameters: []
      responses:
        '200':
          description: company created
        '422':
          description: Title cannot be blank
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createCompany'
        required: true
    get:
      summary: List all companies in your account
      tags:
      - Companies
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: the default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: ' show summarized data information - true/false'
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
  /api/v1/companies/{id}:
    put:
      summary: Update company attributes
      tags:
      - Companies
      parameters:
      - name: id
        in: path
        required: true
        description: company id
        schema:
          type: integer
      responses:
        '200':
          description: company updated
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateCompany'
        required: true
    get:
      summary: Get company by id
      tags:
      - Companies
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: company id
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: company not found
components:
  schemas:
    CompanyBaseRequest:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          properties:
            name:
              type: string
              description: the company name
            address:
              type: string
              description: address of the company
            web:
              type: string
              description: 'link to the company web page '
            contact:
              type: string
              description: 'contacts '
            email:
              type: string
              description: 'email '
            fax:
              type: string
              description: 'fax number '
            description:
              type: string
              description: 'general description '
    updateCompany:
      allOf:
      - $ref: '#/components/schemas/CompanyBaseRequest'
    createCompany:
      allOf:
      - $ref: '#/components/schemas/CompanyBaseRequest'
      - type: object
        properties:
          item:
            type: object
            required:
            - name
