openapi: 3.0.0
info:
  title: Labguru Antibodies Rodent Specimens API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Rodent Specimens
paths:
  /api/v1/rodent_specimens:
    post:
      summary: Creates a rodent specimen
      tags:
      - Rodent Specimens
      parameters: []
      responses:
        '201':
          description: rodent specimen created
        '422':
          description: invalid request - Status can't be blank
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createRodentSpecimen'
        required: true
    get:
      summary: List all Rodent Specimens in your account
      tags:
      - Rodent Specimens
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: the default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: ' show summarized data information - true/false'
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
  /api/v1/rodent_specimens/{id}:
    put:
      summary: Update rodent specimen attributes
      tags:
      - Rodent Specimens
      parameters:
      - name: id
        in: path
        required: true
        description: rodent specimen id
        schema:
          type: integer
      responses:
        '200':
          description: rodent specimen updated
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateRodentSpecimen'
        required: true
    get:
      summary: Get rodent specimen by id
      tags:
      - Rodent Specimens
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: rodent specimen id
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: rodent specimen not found
components:
  schemas:
    createRodentSpecimen:
      allOf:
      - $ref: '#/components/schemas/RodentSpecimenBaseRequest'
      - type: object
        properties:
          item:
            type: object
            required:
            - name
            - status
    RodentSpecimenBaseRequest:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          properties:
            name:
              type: string
              description: The name of the rodent specimen
            status:
              type: string
              description: 'the status of the rodent: alive, dead, missing, sacrificed'
            description:
              type: string
              description: Description of the rodent specimen
            alternative_name:
              type: string
              description: additional name for the rodent specimen
            owner_id:
              type: integer
              description: id of the owner - by default it's your member id
            genotype:
              type: string
              description: genotype
            phenotype:
              type: string
              description: phenotype
            ear_tag:
              type: string
              description: ear tag
            coat_tag:
              type: string
              description: coat tag
            sex:
              type: string
              description: 'sex of the rodent: male, female, unknown'
            ethics:
              type: string
              description: ethics approval id
            dob:
              type: string
              format: date
              description: Date of birth (yyyy-mm-dd)
            dod:
              type: string
              format: date
              description: Date of death (yyyy-mm-dd)
            source:
              type: string
              description: source
    updateRodentSpecimen:
      allOf:
      - $ref: '#/components/schemas/RodentSpecimenBaseRequest'
