openapi: 3.0.0
info:
  title: Labguru Antibodies Search API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Search
paths:
  /api/v1/searches/global_search:
    get:
      summary: Get search results
      tags:
      - Search
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: size
        in: query
        description: 'number of results per page example: 20'
        required: true
        schema:
          type: integer
      - name: term
        in: query
        description: 'search term, example: ant'
        required: true
        schema:
          type: string
      - name: model
        in: query
        description: 'filter by model name, example: Antibody'
        schema:
          type: string
      - name: page
        in: query
        description: the default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: show summarized data information - true/false
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
