openapi: 3.0.0
info:
  title: Labguru Antibodies Compound Parent Structures API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Compound Parent Structures
paths:
  /api/v2/compound_parent_structures:
    get:
      summary: List all compound parent structures
      tags:
      - Compound Parent Structures
      description: Returns a list of all compound parent structures.
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: not found
  /api/v2/compound_parent_structures/{id}:
    /api/v2/compound_parent_structures/{id}: null
    get:
      summary: Get a compound parent structure by ID
      tags:
      - Compound Parent Structures
      description: Returns a single compound parent structure by its ID.
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: not found
    put:
      summary: Update a compound parent structure by ID
      tags:
      - Compound Parent Structures
      description: Updates a compound parent structure with the specified ID.
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - token
              properties:
                token:
                  type: string
                  example: YOUR TOKEN IS HERE
                parent_structure:
                  type: object
                  properties:
                    owner_id:
                      type: string
                      description: The ID of the owner
                      example: '2'
                    name:
                      type: string
                      description: The name of the parent structure
                      example: Updated Parent Structure Name
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: fa0708b0-4dad-4b44-97bc-9284492614d6
                  id:
                    type: integer
                    example: 1
                  cd_id:
                    type: integer
                    example: 1
                  member_id:
                    type: integer
                    example: 7
                  owner_id:
                    type: integer
                    example: 7
                  updated_at:
                    type: string
                    format: date-time
                    example: '2025-03-16T16:25:17.000+02:00'
                  created_at:
                    type: string
                    format: date-time
                    example: '2024-11-13T11:13:35.000+02:00'
                  member:
                    type: string
                    nullable: true
                  description:
                    type: string
                    nullable: true
                  auto_name:
                    type: string
                    example: CP-24.0001
                  cas:
                    type: string
                    nullable: true
                  formula:
                    type: string
                    nullable: true
                  molar_mass:
                    type: number
                    nullable: true
                  density:
                    type: number
                    nullable: true
                  boiling_point:
                    type: number
                    nullable: true
                  melting_point:
                    type: number
                    nullable: true
                  hazards:
                    type: string
                    nullable: true
                  purchasable:
                    type: boolean
                    nullable: true
                  composition:
                    type: string
                    example: C (77.21%), Cl (22.79%)
                  smiles:
                    type: string
                    example: C1CCCC2(C1)[ClH]CCCC2
                  canonical_smiles:
                    type: string
                    example: C1CCC2(CC1)CCCC[ClH]2
                  inchi:
                    type: string
                    example: InChI=1S/C10H19Cl/c1-2-6-10(7-3-1)8-4-5-9-11-10/h11H,1-9H2
                  hba:
                    type: integer
                    example: 19
                  hbd:
                    type: integer
                    example: 1
                  num_hvy_atoms:
                    type: integer
                    nullable: true
                  num_rotors:
                    type: integer
                    example: 0
                  polar_surface_area:
                    type: string
                    example: '0.0'
                  logp:
                    type: string
                    example: '3.0'
                  num_aromatic:
                    type: integer
                    example: 0
                  num_aliphatic:
                    type: integer
                    example: 2
                  chemical_formula:
                    type: string
                    example: C10H19Cl
                  molecular_weight:
                    type: string
                    example: '174.0'
                  sp3:
                    type: string
                    example: '1.0'
                  l5:
                    type: boolean
                    example: false
                  manufacturer:
                    type: string
                    nullable: true
                  web_page:
                    type: string
                    nullable: true
                  image:
                    type: string
                    example: /user_assets/61/depictions/1/original/depiction.png
                  name:
                    type: string
                    example: Compound Nov 13 2024, 11:13:35
                  url:
                    type: string
                    example: /biocollections/compounds/1
                  owner:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 7
                      name:
                        type: string
                        example: Roee Biran
                      url:
                        type: string
                        example: /admin/members/7
                  location:
                    type: string
                    nullable: true
                  parents:
                    type: string
                    nullable: true
                  catalog_number:
                    type: string
                    nullable: true
                  produce_by:
                    type: string
                    nullable: true
                  price_with_currency:
                    type: string
                    nullable: true
                  units:
                    type: string
                    nullable: true
                  company_id:
                    type: integer
                    nullable: true
                  unit_size_to_display:
                    type: string
                    nullable: true
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: not found
        '422':
          description: unprocessable entity
  /api/v2/compound_parent_structures/{id}/compounds:
    get:
      summary: List compounds for a compound parent structure
      tags:
      - Compound Parent Structures
      description: Returns a list of compounds associated with the specified compound parent structure.
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: success
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '404':
          description: not found
