openapi: 3.0.0
info:
  title: Labguru Antibodies Generic Items API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Generic Items
paths:
  /api/v1/biocollections/{generic_collection_name}:
    post:
      summary: Add a generic item
      tags:
      - Generic Items
      parameters:
      - name: generic_collection_name
        in: path
        required: true
        description: generic collection name
        schema:
          type: string
      responses:
        '201':
          description: generic item created
        '422':
          description: invalid request - name can't be blank
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createGenericItem'
        required: true
    get:
      summary: List all generic items in your account
      tags:
      - Generic Items
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: generic_collection_name
        in: path
        required: true
        description: generic collection name
        schema:
          type: string
      - name: page
        in: query
        description: the default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: ' show summarized data information - true/false'
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
  /api/v1/biocollections/{generic_collection_name}/{id}:
    put:
      summary: Update generic item attributes
      tags:
      - Generic Items
      parameters:
      - name: generic_collection_name
        in: path
        required: true
        description: generic collection name
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: generic item id
        schema:
          type: integer
      responses:
        '200':
          description: vector updated
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateGenericItem'
        required: true
    get:
      summary: Get generic item by id
      tags:
      - Generic Items
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: generic_collection_name
        in: path
        required: true
        description: generic collection name
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: generic item id
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: generic item not found
components:
  schemas:
    GenericItemBaseRequest:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          properties:
            name:
              type: string
              description: generic item name
            description:
              type: string
              description: Text description for this generic item
    createGenericItem:
      allOf:
      - $ref: '#/components/schemas/GenericItemBaseRequest'
      - type: object
        properties:
          item:
            type: object
            required:
            - name
    updateGenericItem:
      allOf:
      - $ref: '#/components/schemas/GenericItemBaseRequest'
