openapi: 3.2.0
info:
  title: Labguru Flies API
  description: 'Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.


    Join our dedicated Slack channel

    to be in direct contact with our API team and be informed about the latest updates.


    ***API introduction and overview***'
  version: v1
tags:
- name: Flies
paths:
  /api/v1/flies:
    post:
      summary: Create a Fly
      tags:
      - Flies
      description: Create a fly.
      parameters: []
      responses:
        '201':
          description: OK
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createFly'
        required: true
      operationId: postApiV1Flies
      x-operation-id-source: derived
    get:
      summary: List all flies in your account
      tags:
      - Flies
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: The default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: Show summarized data information - true/false
        schema:
          type: string
      description: List all flies.
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: getApiV1Flies
      x-operation-id-source: derived
  /api/v1/flies/{id}:
    put:
      summary: Update a fly
      tags:
      - Flies
      description: Update a fly.
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the fly
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateFly'
        required: true
      operationId: putApiV1FliesById
      x-operation-id-source: derived
    get:
      summary: Get fly by id
      tags:
      - Flies
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: The ID of the fly
        schema:
          type: integer
      description: Get a fly by ID.
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: getApiV1FliesById
      x-operation-id-source: derived
components:
  schemas:
    createFly:
      allOf:
      - $ref: '#/components/schemas/FlyBaseRequest'
      - type: object
        properties:
          item:
            type: object
            required:
            - name
    updateFly:
      allOf:
      - $ref: '#/components/schemas/FlyBaseRequest'
    FlyBaseRequest:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          properties:
            name:
              type: string
              description: The name of the fly
            owner_id:
              type: integer
              description: id of the owner - by default it's your member id
            source:
              type: string
              description: Origin of the fly.
            genotype:
              type: string
              description: Genetic makeup.
            phenotype:
              type: string
              description: Observable characteristics.
            breakpoints_insertions:
              type: string
              description: Genetic insertion points.
            ch_number:
              type: string
              description: Chromosome number.
            ch_te:
              type: string
              description: Transposable element in chromosome.
            description:
              type: string
              description: Description of the fly
