openapi: 3.0.0
info:
  title: Labguru Antibodies Members API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Members
paths:
  /api/v1/admin/members:
    get:
      summary: List all members in the account
      tags:
      - Members
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: filter
        in: query
        description: The name/id of the user in the following format - {"name":"Labuser Biodata"} / {"id":11}
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
