openapi: 3.0.0
info:
  title: Labguru Antibodies Flies API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Flies
paths:
  /api/v1/flies:
    post:
      summary: Create a Fly
      tags:
      - Flies
      description: 'Create a fly.

        '
      parameters: []
      responses:
        '201':
          description: OK
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createFly'
        required: true
    get:
      summary: List all flies in your account
      tags:
      - Flies
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: The default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: Show summarized data information - true/false
        schema:
          type: string
      description: 'List all flies.

        '
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
  /api/v1/flies/{id}:
    put:
      summary: Update a fly
      tags:
      - Flies
      description: 'Update a fly.

        '
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the fly
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateFly'
        required: true
    get:
      summary: Get fly by id
      tags:
      - Flies
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: The ID of the fly
        schema:
          type: integer
      description: 'Get a fly by ID.

        '
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
components:
  schemas:
    updateFly:
      allOf:
      - $ref: '#/components/schemas/FlyBaseRequest'
    createFly:
      allOf:
      - $ref: '#/components/schemas/FlyBaseRequest'
      - type: object
        properties:
          item:
            type: object
            required:
            - name
    FlyBaseRequest:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          properties:
            name:
              type: string
              description: The name of the fly
            owner_id:
              type: integer
              description: id of the owner - by default it's your member id
            source:
              type: string
              description: Origin of the fly.
            genotype:
              type: string
              description: Genetic makeup.
            phenotype:
              type: string
              description: Observable characteristics.
            breakpoints_insertions:
              type: string
              description: Genetic insertion points.
            ch_number:
              type: string
              description: Chromosome number.
            ch_te:
              type: string
              description: Transposable element in chromosome.
            description:
              type: string
              description: Description of the fly
