openapi: 3.0.0
info:
  title: Labguru Antibodies Maintenance types API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Maintenance types
paths:
  /api/v1/maintenance_types:
    post:
      summary: Creates a Maintenance type
      tags:
      - Maintenance types
      parameters: []
      responses:
        '201':
          description: maintenance type created
        '422':
          description: invalid request - Name can't be blank
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createMaintenanceType'
        required: true
    get:
      summary: List all maintenance types in your account
      tags:
      - Maintenance types
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: the default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: ' show summarized data information - true/false'
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
  /api/v1/maintenance_types/{id}:
    put:
      summary: Update maintenance type
      tags:
      - Maintenance types
      parameters:
      - name: id
        in: path
        required: true
        description: maintenance type id
        schema:
          type: integer
      responses:
        '200':
          description: maintenance type updated
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateMaintenanceType'
        required: true
    get:
      summary: Get maintenance type by id
      tags:
      - Maintenance types
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: maintenance type id
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: maintenance type not found
components:
  schemas:
    createMaintenanceType:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          required:
          - name
          properties:
            name:
              type: string
              description: The name of the maintenance type
    updateMaintenanceType:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          required:
          - name
          properties:
            name:
              type: string
              description: The new name of the maintenance type
