openapi: 3.0.0
info:
  title: Labguru Antibodies Events API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Events
paths:
  /api/v1/events:
    post:
      summary: Add an event
      tags:
      - Events
      parameters: []
      responses:
        '201':
          description: event created
        '422':
          description: Repeats frame should be a number and greater than 0
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createEvent'
        required: true
    get:
      summary: List all event in your account
      tags:
      - Events
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: the default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: ' show summarized data information - true/false'
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
  /api/v1/events/{id}:
    put:
      summary: Update event attributes
      tags:
      - Events
      parameters:
      - name: id
        in: path
        required: true
        description: event id
        schema:
          type: integer
      responses:
        '200':
          description: event updated
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateEvent'
        required: true
    get:
      summary: Get event by id
      tags:
      - Events
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: event id
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: event not found
    delete:
      summary: Delete event
      tags:
      - Events
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: event id
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: page not found
components:
  schemas:
    createEvent:
      allOf:
      - $ref: '#/components/schemas/EventBaseRequest'
      - type: object
        properties:
          item:
            type: object
            required:
            - name
            - start_date
            - end_date
    EventBaseRequest:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          properties:
            name:
              type: string
              description: event title
            start_date:
              type: string
              format: date
              description: the event start date
            end_date:
              type: string
              format: date
              description: the event end date
            description:
              type: string
              description: ' text description for this event'
            notify_members:
              type: string
              description: 'who should be notified regarding the event: notify only me =[1], notify all participants = [-1], none =[0]'
              example: '[0]'
            notify_at:
              type: string
              format: date
              description: when to notify about the event
            is_fullday_event:
              type: boolean
              description: true/false
            repeats:
              type: integer
              description: 1/0
            repeat_frame:
              type: string
              description: the time frame which the event will be repeated at - Never, days, weeks, months
              example: Never
            eventable_id:
              type: integer
              description: the equipment id which the event is related to
            eventable_type:
              type: string
              description: the item class name - System::Instrument
              example: System::Instrument
    updateEvent:
      allOf:
      - $ref: '#/components/schemas/EventBaseRequest'
