openapi: 3.0.0
info:
  title: Labguru Antibodies SOPs API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: SOPs
paths:
  /api/v1/sops:
    post:
      summary: Creates a SOP
      tags:
      - SOPs
      parameters: []
      responses:
        '201':
          description: SOP created
        '422':
          description: invalid request - Name can't be blank
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createSOP'
        required: true
    get:
      summary: List all SOPs in your account
      tags:
      - SOPs
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: the default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: ' show summarized data information - true/false'
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
  /api/v1/sops/{id}:
    put:
      summary: Update SOP
      tags:
      - SOPs
      parameters:
      - name: id
        in: path
        required: true
        description: SOPs id
        schema:
          type: integer
      responses:
        '200':
          description: SOP updated
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateSOP'
        required: true
    get:
      summary: Get SOP by id
      tags:
      - SOPs
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: SOP id
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: SOP not found
components:
  schemas:
    createSOP:
      allOf:
      - $ref: '#/components/schemas/SOPBaseRequest'
      - type: object
        properties:
          item:
            type: object
            required:
            - title
    updateSOP:
      allOf:
      - $ref: '#/components/schemas/SOPBaseRequest'
    SOPBaseRequest:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          properties:
            title:
              type: string
              description: The name of the SOP
