openapi: 3.2.0
info:
  title: Labguru Members API
  description: 'Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.


    Join our dedicated Slack channel

    to be in direct contact with our API team and be informed about the latest updates.


    ***API introduction and overview***'
  version: v1
tags:
- name: Members
paths:
  /api/v1/admin/members:
    get:
      summary: List all members in the account
      tags:
      - Members
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: filter
        in: query
        description: The name/id of the user in the following format - {"name":"Labuser Biodata"} / {"id":11}
        schema:
          type: string
      responses:
        '200':
          description: success
        '404':
          description: page not found
      operationId: getApiV1AdminMembers
      x-operation-id-source: derived
