openapi: 3.0.0
info:
  title: Labguru Antibodies Plasmids API
  description: "Labguru API is a JSON / REST based API, get started by reviewing the documentation below or code samples.<br>\n        Join our dedicated [Slack channel](https://join.slack.com/t/labgurus/shared_invite/zt-199glfagl-QZQ_bKl7vLAi8CQSuNrRug)\n        to be in direct contact with our API team and be informed about the latest updates.<br>\n        ***[API introduction and overview](https://help.labguru.com/en/articles/6149483-api-introduction-and-overview)***"
  version: v1
tags:
- name: Plasmids
paths:
  /api/v1/plasmids:
    post:
      summary: Create a plasmid
      tags:
      - Plasmids
      description: 'Create a plasmid.

        '
      parameters: []
      responses:
        '201':
          description: Created
        '422':
          description: Invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createPlasmid'
        required: true
    get:
      summary: List all plasmids in your account
      tags:
      - Plasmids
      description: 'List all plasmids.

        '
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: The default call is with page = 1
        schema:
          type: integer
      - name: meta
        in: query
        description: Show summarized data information - true/false
        schema:
          type: string
      responses:
        '200':
          description: OK
        '404':
          description: Not found
        '401':
          description: 'Error: Unauthorized'
  /api/v1/plasmids/{id}:
    put:
      summary: Update a plasmid
      tags:
      - Plasmids
      description: 'Update plasmid.

        '
      parameters:
      - name: id
        in: path
        required: true
        description: The ID of the plasmid
        schema:
          type: integer
      responses:
        '200':
          description: plasmid updated
        '422':
          description: invalid request
        '401':
          description: 'Error: Unauthorized'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updatePlasmid'
        required: true
    get:
      summary: Get plasmid by ID
      tags:
      - Plasmids
      description: 'Get plasmid by ID.

        '
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: The ID of the plasmid
        schema:
          type: integer
      responses:
        '200':
          description: success
        '404':
          description: Not found
        '401':
          description: 'Error: Unauthorized'
components:
  schemas:
    PlasmidBaseRequest:
      type: object
      required:
      - token
      properties:
        token:
          type: string
          example: YOUR TOKEN IS HERE
        item:
          type: object
          properties:
            title:
              type: string
              description: The name of the plasmid
            alternative_name:
              type: string
              description: Any alternative name by which the plasmid may be known
            owner_id:
              type: integer
              description: id of the owner - by default it's your member id
            length:
              type: integer
              description: The total number of base pairs (bp) in the plasmid’s DNA sequence.
            usage:
              type: string
              description: Intended or common uses of the plasmid (cloning, gene expression, etc.)
            host:
              type: string
              description: Typical host organism for the plasmid
            resistance:
              type: string
              description: Antibiotic resistance markers present in the plasmid
            clone_number:
              type: string
              description: Unique identifier or clone number associated with the plasmid
            source:
              type: string
              description: Origin or provider of the plasmid
            sequence:
              type: string
              description: The nucleotide sequence of the plasmid
            description:
              type: string
              description: A detailed description of the plasmid
    updatePlasmid:
      allOf:
      - $ref: '#/components/schemas/PlasmidBaseRequest'
    createPlasmid:
      allOf:
      - $ref: '#/components/schemas/PlasmidBaseRequest'
      - type: object
        properties:
          item:
            type: object
            required:
            - title
